spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: express-service
          uri: lb://GATEWAY-SERVICE
          predicates:
            - Path=/api/**
      globalcors:
        cors-configurations:
          '[/**]': # Matches all paths
            allowedOrigins: "*" # Allow all origins
            allowedMethods: "*" # Allow all HTTP methods (GET, POST, PUT, DELETE, etc.)
    discovery:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/  # Eureka server URL
      enabled: true
server:
  port: 8888
